name: Build Profile README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci
      - name: Update README
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |-
          npm start
          cat README.md
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
